import { CropDefinition, FishDefinition, FishingRod, BaitDefinition, InventoryItem, DailyQuest, UserProfile, SoilPlot } from '../types';

export const CROPS: CropDefinition[] = [
  {
    id: 'rice',
    name: 'Lua Nuoc',
    seedName: 'Hat Giong Lua',
    growDuration: 12, // 12 seconds for active fun gameplay
    seedPrice: 20,
    sellPrice: 48,
    expReward: 10,
    icon: '🌾',
    seedIcon: '🌱',
    description: 'Cay lua hat vang triu hat, dac san dong que Avatar de trong lon nhanh.',
    levelRequired: 1,
  },
  {
    id: 'carrot',
    name: 'Ca Rot Do',
    seedName: 'Hat Ca Rot',
    growDuration: 22,
    seedPrice: 45,
    sellPrice: 110,
    expReward: 20,
    icon: '🥕',
    seedIcon: '🌱',
    description: 'Ca rot gion ngot, giau dinh duong, thu hoach dem ban gia cao.',
    levelRequired: 1,
  },
  {
    id: 'tomato',
    name: 'Ca Chua Bi',
    seedName: 'Hat Ca Chua',
    growDuration: 35,
    seedPrice: 80,
    sellPrice: 210,
    expReward: 35,
    icon: '🍅',
    seedIcon: '🌱',
    description: 'Chum ca chua mong nuoc, lai buon nong san thu mua so luong lon.',
    levelRequired: 2,
  },
  {
    id: 'watermelon',
    name: 'Dua Hau Do',
    seedName: 'Hat Dua Hau',
    growDuration: 50,
    seedPrice: 150,
    sellPrice: 420,
    expReward: 60,
    icon: '🍉',
    seedIcon: '🌱',
    description: 'Trai dua hau mat ruoi, thu hoach mang lai loi nhuan lon.',
    levelRequired: 3,
  },
  {
    id: 'rose',
    name: 'Hoa Hong Do',
    seedName: 'Hat Hoa Hong',
    growDuration: 70,
    seedPrice: 240,
    sellPrice: 680,
    expReward: 100,
    icon: '🌹',
    seedIcon: '🌱',
    description: 'Bong hong kieu sa co the dem tang ban be cong vien hoac ban lay Xu.',
    levelRequired: 4,
  },
  {
    id: 'strawberry',
    name: 'Dau Tay Vang',
    seedName: 'Hat Dau Vang',
    growDuration: 90,
    seedPrice: 400,
    sellPrice: 1200,
    expReward: 180,
    icon: '🍓',
    seedIcon: '✨',
    description: 'Trai dau quy toc cua thi tran Avatar, loi nhuan cuc khung.',
    levelRequired: 5,
  }
];

export const FISH_SPECIES: FishDefinition[] = [
  {
    id: 'fish_carp',
    name: 'Ca Ro Dong',
    rarity: 'common',
    sellPrice: 60,
    expReward: 12,
    icon: '🐟',
    description: 'Ca ro dong quen thuoc nhay lach tach o ven ho.',
    difficulty: 1,
    minBaitLevel: 1,
  },
  {
    id: 'fish_gold',
    name: 'Ca Chep Vang',
    rarity: 'common',
    sellPrice: 120,
    expReward: 24,
    icon: '🐠',
    description: 'Ca chep ong anh mang lai may man cho cac can thu Avatar.',
    difficulty: 2,
    minBaitLevel: 1,
  },
  {
    id: 'fish_catfish',
    name: 'Ca Tre Mun',
    rarity: 'rare',
    sellPrice: 260,
    expReward: 50,
    icon: '🐡',
    description: 'Ca da tron boi khoe, giat can rat da tay.',
    difficulty: 3,
    minBaitLevel: 1,
  },
  {
    id: 'fish_clown',
    name: 'Ca He San Ho',
    rarity: 'rare',
    sellPrice: 380,
    expReward: 75,
    icon: '🐟',
    description: 'Chu ca he Nemo ruc ro boi tu nhanh song vao ho sinh thai.',
    difficulty: 3,
    minBaitLevel: 2,
  },
  {
    id: 'fish_ray',
    name: 'Ca Duoi Khong Lo',
    rarity: 'epic',
    sellPrice: 750,
    expReward: 150,
    icon: '🦑',
    description: 'Ca duoi khong lo quay song manh, can thu phai canh nhip that kheo.',
    difficulty: 4,
    minBaitLevel: 2,
  },
  {
    id: 'fish_shark',
    name: 'Ca Map Can Cap',
    rarity: 'epic',
    sellPrice: 1500,
    expReward: 300,
    icon: '🦈',
    description: 'Hang hiem o vung nuoc sau, dem ban doi duoc nui Xu.',
    difficulty: 4,
    minBaitLevel: 3,
  },
  {
    id: 'fish_dragon',
    name: 'Ca Rong Kim Long',
    rarity: 'legendary',
    sellPrice: 4500,
    expReward: 800,
    icon: '🐉',
    description: 'Huyen thoai ho cau Avatar! Vay vang ruc ro, bieu tuong dai gia.',
    difficulty: 5,
    minBaitLevel: 3,
  },
];

export const FISHING_RODS: FishingRod[] = [
  {
    id: 'rod_bamboo',
    name: 'Can Tre Dong Que',
    durability: 30,
    maxDurability: 30,
    luckBonus: 0,
    priceXu: 0,
    priceLuong: 0,
    icon: '🎋',
    description: 'Can cau moc mac cap ban dau cho moi nong dan Avatar.',
  },
  {
    id: 'rod_lotus',
    name: 'Can Truc Sen Ngoc',
    durability: 60,
    maxDurability: 60,
    luckBonus: 20,
    priceXu: 800,
    priceLuong: 0,
    icon: '🎣',
    description: 'Tang 20% ti le bat duoc ca hiem va ca bu.',
  },
  {
    id: 'rod_carbon',
    name: 'Can May Carbon',
    durability: 120,
    maxDurability: 120,
    luckBonus: 45,
    priceXu: 2500,
    priceLuong: 5,
    icon: '⚡',
    description: 'Day cuoc sieu ben, keo ca cuc nhay va tang 45% may man.',
  },
  {
    id: 'rod_gold',
    name: 'Can Hoang Kim Rong',
    durability: 300,
    maxDurability: 300,
    luckBonus: 85,
    priceXu: 8000,
    priceLuong: 25,
    icon: '🌟',
    description: 'Vat pham quy toc phat sang lap lanh, ty le cau trung Rong Vang cuc cao!',
  },
];

export const BAITS: BaitDefinition[] = [
  {
    id: 'bait_worm',
    name: 'Giun Dat Tuoi',
    priceXu: 15,
    count: 5,
    tier: 1,
    icon: '🪱',
    description: 'Moi cau binh dan, ca ro va ca chep rat thich.',
  },
  {
    id: 'bait_shrimp',
    name: 'Tom Song Bung Nhay',
    priceXu: 50,
    count: 5,
    tier: 2,
    icon: '🦐',
    description: 'Moi tanh kich thich ca to va ca quay manh can cau.',
  },
  {
    id: 'bait_magic',
    name: 'Moi Than Ky Loi Ngu',
    priceXu: 150,
    count: 3,
    tier: 3,
    icon: '🔮',
    description: 'Tam huong thom bi truyen cua thi tran, chuyen san thuy quai ca rong.',
  },
];

export const FASHION_SHOP_ITEMS = [
  {
    id: 'hat_straw',
    name: 'Non La Nong Dan',
    type: 'hat' as const,
    priceXu: 300,
    priceLuong: 0,
    icon: '👒',
    value: 'straw',
    description: 'Non la truyen thong che mua che nang tren canh dong.',
  },
  {
    id: 'hat_cowboy',
    name: 'Mu Cao Boi Texas',
    type: 'hat' as const,
    priceXu: 900,
    priceLuong: 0,
    icon: '🤠',
    value: 'cowboy',
    description: 'Phong cach lang tu mien tay cuc chat khi di dao cong vien.',
  },
  {
    id: 'hat_crown',
    name: 'Vuong Mien Hoang Gia',
    type: 'hat' as const,
    priceXu: 0,
    priceLuong: 20,
    icon: '👑',
    value: 'crown',
    description: 'Trang suc vuong gia dinh kim cuong danh rieng cho quy toc.',
  },
  {
    id: 'glasses_cool',
    name: 'Kinh Ram Den Ngau',
    type: 'glasses' as const,
    priceXu: 450,
    priceLuong: 0,
    icon: '🕶️',
    value: 'black',
    description: 'Kinh mat den huyen thoai khien moi nguoi ngoai nhin.',
  },
  {
    id: 'wings_angel',
    name: 'Canh Thien Than Trang',
    type: 'wings' as const,
    priceXu: 0,
    priceLuong: 35,
    icon: '🪽',
    value: 'angel',
    description: 'Doi canh thien than huyen ao vo canh bay bong giua thi tran Avatar!',
  },
  {
    id: 'wings_demon',
    name: 'Canh Ac Ma Lua',
    type: 'wings' as const,
    priceXu: 0,
    priceLuong: 35,
    icon: '🦇',
    value: 'demon',
    description: 'Canh doi quy vuong ma mi, the hien dang cap dan choi.',
  },
];

export const INITIAL_PLOTS: SoilPlot[] = Array.from({ length: 12 }, (_, i) => ({
  id: i + 1,
  cropId: i < 3 ? 'rice' : null,
  plantedAt: i < 3 ? Date.now() - 6000 : null,
  watered: i < 3,
  hasPest: false,
  fertilized: false,
  }));

export const INITIAL_DAILY_QUESTS: DailyQuest[] = [
  {
    id: 'quest_harvest',
    title: 'Thu hoach 4 luong cay trong',
    progress: 0,
    target: 4,
    rewardXu: 300,
    rewardExp: 50,
    completed: false,
    claimed: false,
    icon: '🌾',
  },
  {
    id: 'quest_fish',
    title: 'Cau thanh cong 3 con ca o ho',
    progress: 0,
    target: 3,
    rewardXu: 350,
    rewardExp: 60,
    completed: false,
    claimed: false,
    icon: '🎣',
  },
  {
    id: 'quest_casino',
    title: 'Thu van may 1 van Bau Cua hoac Vong Quay',
    progress: 0,
    target: 1,
    rewardXu: 200,
    rewardExp: 40,
    completed: false,
    claimed: false,
    icon: '🎲',
  },
  {
    id: 'quest_chicken',
    title: 'Thu thap trung ga trong trang trai',
    progress: 0,
    target: 2,
    rewardXu: 250,
    rewardExp: 40,
    completed: false,
    claimed: false,
    icon: '🥚',
  },
];

export const DEFAULT_USER: UserProfile = {
  id: 'user_avatar_default',
  username: 'NongDanChamChi',
  nickname: 'Can Thu Avatar',
  gender: 'male',
  level: 1,
  exp: 40,
  maxExp: 100,
  energy: 100,
  maxEnergy: 100,
  xu: 1250, // Starter money in coins
  luong: 15, // Starter gold nuggets
  appearance: {
    skinColor: '#fcd34d',
    hairStyle: 'spiky',
    hairColor: '#451a03',
    shirtStyle: 'tshirt',
    shirtColor: '#2563eb',
    pantsStyle: 'jeans',
    pantsColor: '#1e3a8a',
    hat: 'straw',
    handheld: 'rod_bamboo',
    glasses: 'black',
  },
  farmPlots: INITIAL_PLOTS,
  chickens: [
    { id: 1, fed: true, eggsReady: true, fedAt: Date.now() - 10000 },
    { id: 2, fed: false, eggsReady: false, fedAt: Date.now() },
  ],
  inventory: [
    { id: 'rice_seed', name: 'Hat Giong Lua', type: 'seed', count: 6, sellPrice: 10, icon: '🌱', description: 'Gieo vao o dat de trong lua' },
    { id: 'carrot_seed', name: 'Hat Ca Rot', type: 'seed', count: 4, sellPrice: 20, icon: '🌱', description: 'Gieo vao o dat de trong ca rot' },
    { id: 'bait_worm', name: 'Giun Dat Tuoi', type: 'bait', count: 8, sellPrice: 5, icon: '🪱', description: 'Moi cau dung o ho nuoc' },
    { id: 'fertilizer', name: 'Phan Bon Nhanh', type: 'fertilizer', count: 3, sellPrice: 30, icon: '🧪', description: 'Giam 50% thoi gian lon cua cay trong' },
  ],
  equippedRodId: 'rod_bamboo',
  equippedBaitId: 'bait_worm',
  currentArea: 'farm',
  stats: {
    cropsHarvested: 0,
    fishCaught: 0,
    miniGamesPlayed: 0,
    miniGamesWon: 0,
    moneyEarned: 0,
  },
  quests: INITIAL_DAILY_QUESTS,
  lastLogin: Date.now(),
};
