import { adminCreateKeys, adminGetAllKeys } from '../keyManager.js';

// Parse command line arguments
const args = process.argv.slice(2);
let count = 5;
let prefix = 'VIP';
let role = 'player';
let xu = 50000;
let luong = 20;
let note = 'Generated by Admin CLI';

for (const arg of args) {
  if (arg.startsWith('--count=')) count = parseInt(arg.split('=')[1]);
  if (arg.startsWith('--prefix=')) prefix = arg.split('=')[1].toUpperCase();
  if (arg.startsWith('--role=')) role = arg.split('=')[1];
  if (arg.startsWith('--xu=')) xu = parseInt(arg.split('=')[1]);
  if (arg.startsWith('--luong=')) luong = parseInt(arg.split('=')[1]);
  if (arg.startsWith('--note=')) note = arg.split('=')[1];
}

console.log(`\n======================================================`);
console.log(`🔑 TIẾN HÀNH SINH ${count} MÃ KEY MỚI (${role.toUpperCase()})...`);
console.log(`💰 Tặng kèm: ${xu.toLocaleString()} Xu | ${luong} Lượng`);
console.log(`======================================================`);

const newKeys = adminCreateKeys({ count, prefix, role, xu, luong, note });

console.log(`\n🎉 ĐÃ TẠO THÀNH CÔNG ${newKeys.length} MÃ KEY:`);
newKeys.forEach((k, idx) => {
  console.log(` [${idx + 1}] ${k}`);
});
console.log(`\n👉 Bạn có thể gửi các mã key trên cho người chơi để đăng nhập vào game!`);
console.log(`======================================================\n`);
